openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:7071/api

paths:
  /accounts:
    get:
      summary: Lists the financial accounts.
      responses:
        '200':
          description: A valid response with one or more accounts.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  recordCode:
                    type: string
                  recordId:
                    type: string
                  balance:
                    type: number
                  nextAccountNumber:
                    type: string
                  accountSummaries:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        recordId:
                          type: string
                        accountName:
                          type: string
                        balance:
                          type: number
  /account/{id}:
    get:
      summary: Lists the account and recent transactions.
      parameters:
        - name: id
          in: path
          required: true
          description: The account id for programmatic access.
          schema:
            type: string
      responses:
        '200':
          description: A valid response with the account information and a list of recent transactions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  recordId:
                    type: string
                  accountName:
                    type: string
                  balance:
                    type: number
                  nextTransactionRecordId:
                    type: string
  /account:
    put:
      summary: Reserves the next account with a new account number, name, and starting balance.
      requestBody:
        description: The minimal information to reserve the next accounts.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accountName:
                  type: string
                balance:
                  type: number
      responses:
        '200':
          description: A valid response with the account information and a list of recent transactions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  recordId:
                    type: string
                  accountName:
                    type: string
                  balance:
                    type: number
                  nextTransactionRecordId:
                    type: string


